# Data from BCEAO

In [1]:
import pandas as pd
import numpy as np

### Commerce extérieur

In [8]:
commerce_exterieur = pd.read_excel("data/bceao-ce.xlsx")
commerce_exterieur.head()

,Pays,Année,Exportations totales,Exportations de produits du cacao,Exportations de cacao en fèves,Exportations de cacao en produits transformés,Exportations de produits du café,Exportations de produits du coton,Exportations de coton graine,Exportations de coton fibre,...,Exportations vers l'UE,Exportations vers la Zone euro,Exportations vers la France,Exportations vers l'Allemagne,Exportations vers l'Italie,Exportations vers les PaysBas,Exportations vers le RoyaumeUni,Exportations vers la Belgique,Exportations vers l'Afrique,Exportations vers l'UEMOA
0,COTE D'IVOIRE,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,COTE D'IVOIRE,1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,COTE D'IVOIRE,1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,COTE D'IVOIRE,1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,COTE D'IVOIRE,1964,73186.0,14001.9,13955.0,46.9,NaN,62.8,NaN,62.8,...,45100.0,NaN,25900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN